source <(curl -sL init.zshell.dev)
zzinit

# This loads all of the files in ~/.config/zsh/lib.
source ~/.config/zsh/loader.zsh
# Custom plugins

# Archive
source ~/.config/zsh/extern/archive/init.zsh

# Archive functions
fpath=(
    ~/.config/zsh/extern/archive/functions
    "${fpath[@]}"
)

# Load on invocation
autoload -Uz archive
autoload -Uz lsarchive
autoload -Uz unarchive
