#!/usr/bin/env bash

function toggle_menu {
    STATE=$(eww active-windows | cut -d':' -f1 | grep $1 )
      if [[ $STATE == $1 ]]; then 
        eww close $1;
    else
        eww open $1;
    fi
}

if [[ $1 == 'toggle_menu' ]]; then toggle_menu $2; fi
