#!/usr/bin/env bash

function toggle_menu {
    MAIN=$(eww get main_monitor)
    STATE=$(eww windows | grep $1$MAIN | awk '{print substr ($0, 0, 1)}')
    if [[ $STATE == '*' ]]; then 
        eww close $1$MAIN;
    else
        eww open $1$MAIN;
    fi
}





if [[ $1 == 'toggle_menu'    ]]; then toggle_menu $2; fi
