colorscheme oxocarbon


# Set up the files for kak-lsp.
# Note: this makes it easier to control things.
nop %sh{
   if [ ! -e "$XDG_CONFIG_HOME/kak-lsp" ]; then
        ln -s "$kak_config/config/kak-lsp" "$XDG_CONFIG_HOME/kak-lsp"
    fi

}


source "%val{config}/autoloader.kak"
